# SPDX-License-Identifier: MIT
# This task checks sha256, downloads, and extracts, and then removes a tarball..
# It takes __hpc_pkg_info dict with name, url, sha256 keys.
# It sets __hpc_pkg_extracted variable with the path of the extracted tarball.
---
- name: Create temp directory for extracting tarball {{ __hpc_pkg_info.name }}
  tempfile:
    state: directory
    prefix: "{{ __hpc_pkg_info.name }}_"
  register: __hpc_pkg_extracted
  changed_when: false

- name: Download package and verify checksum for {{ __hpc_pkg_info.name }}
  get_url:
    url: "{{ __hpc_pkg_info.url }}"
    dest: "{{ __hpc_pkg_extracted.path }}/temp_tarball"
    checksum: sha256:{{ __hpc_pkg_info.sha256 }}
    mode: "0644"
  changed_when: false

- name: Extract tarball for {{ __hpc_pkg_info.name }}
  unarchive:
    src: "{{ __hpc_pkg_extracted.path }}/temp_tarball"
    dest: "{{ __hpc_pkg_extracted.path }}"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
  changed_when: false
